### ISSUE TITLE
can't decode byte 0x81 in position 1341

### ISSUE THREAD

**Issue by xDetroUK** [g-battaglia/kerykeion#38]
I'm trying to create chart SVG chart file with this code:
first = KrInstance("Jack", 1990, 6, 15, 15, 15, "Roma")

name = MakeSvgInstance(second, chart_type="Natal")
name.makeSVG()

and when i try to execute the code i receive this message:

Traceback (most recent call last):
  File "C:\Users\mario\Desktop\University\Please 4.20\RandomTests\test3.py", line 10, in <module>
    name = MakeSvgInstance(second, chart_type="Natal")
  File "C:\Users\mario\AppData\Local\Programs\Python\Python39\lib\site-packages\kerykeion\charts\charts_svg.py", line 139, in __init__
    natal_aspects_instance = NatalAspects(
  File "C:\Users\mario\AppData\Local\Programs\Python\Python39\lib\site-packages\kerykeion\aspects.py", line 25, in __init__
    self._parse_json_settings()
  File "C:\Users\mario\AppData\Local\Programs\Python\Python39\lib\site-packages\kerykeion\aspects.py", line 42, in _parse_json_settings
    settings = json.load(f)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\mario\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1341: character maps to <undefined>

any suggestions ?

**Comment by g-battaglia** [comment]
Hi, I think I've fixed the issue, can you upgrade to versione 3.1.1 and try again?

**Comment by xDetroUK** [comment]
Hi!, i updated the version and tried again but received still receive the same error i tried to execute the following function aswell just as a test :

from kerykeion import CompositeAspects, KrInstance
first = KrInstance("Jack", 1990, 6, 15, 15, 15, "Roma")
second = KrInstance("Jane", 1991, 10, 25, 21, 00, "Roma")

name = CompositeAspects(first, second)
aspect_list = name.get_relevant_aspects()
print(aspect_list[0])

but received again the same error

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1341: character maps to <undefined>

**Comment by paladinic** [comment]
I am also still getting this error.
Tried both Python 3.9 and 3.10
Tred also kerykeion==3.1.6 and 3.1.1

**Comment by paladinic** [comment]
fixed in fork: [https://github.com/paladinic/kerykeion](https://github.com/paladinic/kerykeion)

**Comment by g-battaglia** [comment]
Hi, thank you for your contribution, I made a small change to your fix, can you check if still works pleas?

**Comment by paladinic** [comment]
grazie a te! And I confirm it works for me 👍

**Comment by xDetroUK** [comment]
All works good now, thanks!

**Comment by xDetroUK** [comment]
Is it possible to save the chart image only without the information on the side

**Comment by g-battaglia** [comment]
Yes, you should set the template_type to basic, eg:
```python
MakeSvgInstance(first, chart_type="Composite",
                           second_obj=second, lang="IT", template_type="basic")
```
